// Animecix/build.gradle.kts
// Generated by CloudStream Plugin Builder

version = 1

cloudstream {
    language = "en"
    description = "Auto-generated provider for CloudStream"
    authors = listOf("qera18")
    status = 1
    tvTypes = listOf("Anime", "AnimeMovie", "Movie", "TvSeries")
}

android {
    compileOptions {
        // Align Java compatibility with Kotlin's JVM target (both JVM 11).
        // Omitting this lets Java tasks default to Java 17 and breaks the build.
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11)
    }
}
