// Belgeselx/build.gradle.kts
// Generated by CloudStream Plugin Builder

version = 1

cloudstream {
    language = "en"
    description = "Auto-generated provider for CloudStream"
    authors = listOf("qera18")
    status = 1
    tvTypes = listOf("Anime", "AnimeMovie", "Movie", "TvSeries")
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11)
    }
}
