name: Build Plugins

concurrency:
  group: "build"
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kaynak kodu indir
        uses: actions/checkout@v4
        with:
          path: "src"

      - name: Builds dalını indir
        uses: actions/checkout@v4
        with:
          ref: "builds"
          path: "builds"

      - name: Eski derlemeleri temizle
        run: rm -f $GITHUB_WORKSPACE/builds/*.cs3

      - name: Java 17 kur
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Android SDK kur
        uses: android-actions/setup-android@v4.0.1

      - name: Eklentileri derle
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          shopt -s globstar
          ./gradlew make makePluginsJson --no-daemon
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      - name: Builds dalına gönder
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit --amend -m "Build $GITHUB_SHA" || exit 0
          git push --force
